name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Run tests
      run: yarn test
